/**
 * 0.21 §6-d — HISTÓRICO DA SUPERFÍCIE, verbatim.
 *
 * As descrições das tools carregavam o changelog (0.19.4, beta.26, s3c…) e misturavam duas
 * línguas — 7–10k tokens de schema pagos em TODAS as voltas de um agente. Passam a ≤600
 * caracteres, uma língua; o que lá estava NÃO se apaga: vive aqui, tal e qual estava em
 * tools/list @ 6ea4789 (antes desta fase), e serve-se em sbd://toe/version.surface_history.
 */
export const SURFACE_HISTORY = {
  note: "Descrições das tools tal como eram servidas antes da 0.21 §6-d (verbatim). O changelog vive no CHANGELOG.md e aqui; as descrições servidas hoje só dizem o que a tool faz.",
  captured_at: "0.21 @ 6ea4789 (2026-09-25)",
  tools: {
    "search_sbd_toe_manual": {
      previous_description: "NÃO-NORMATIVO — leitura e orientação, NUNCA caminho para um conjunto de requisitos. Pesquisa semântica sobre os chunks publicados do manual: serve para LER e localizar passagens (e para tu, LLM, formares a tua leitura), não para decidir âmbito. O conjunto de requisitos vem de select_sbd_toe_requirements com activadores DECLARADOS (vocabulário em sbd://toe/activation-vocabulary) — o que aqui sai não selecciona nada e não deve ser citado como se fosse selecção."
    },
    "answer_sbd_toe_manual": {
      previous_description: "SERVE CONTEXTO PARA O TEU MODELO RESPONDER — não responde: a resposta é do modelo do cliente, via sampling, e o juízo é de quem pergunta. Recupera contexto do Manual e pede a resposta final ao modelo do cliente via MCP sampling. Requires sampling support from the MCP client. Without sampling, falls back to formatted retrieval output (same as search_sbd_toe_manual). Prefer search_sbd_toe_manual for clients without sampling support."
    },
    "inspect_sbd_toe_retrieval": {
      previous_description: "Inspects retrieval, context selection and final prompt without requesting an answer from the client model."
    },
    "list_sbd_toe_chapters": {
      previous_description: "Lists SbD-ToE manual chapters with id, canonical title, a clean readableTitle, graduated applicability (all levels true) and derived demand_by_level (0.14.0 — the binary minLevel theory is retired)."
    },
    "query_sbd_toe_entities": {
      previous_description: "Queries manual entities by text, entity type, chapter or risk level."
    },
    "get_sbd_toe_chapter_brief": {
      previous_description: "Returns an operational summary of a chapter: title, objective, role, phases, artefacts (fields are present when the substrate carries them)."
    },
    "plan_sbd_toe_repo_governance": {
      previous_description: "PROJECÇÃO DOS ARTEFACTOS PUBLICADOS — não governa o teu repositório: serve o que o Manual identifica, por capítulo, para tu decidires o que instalas. Lista de artefactos/documentos do SbD-ToE, grouped by chapter, with risk level applicability. Optionally filter by riskLevel (L1/L2/L3). All data comes from the manual indices — nothing is invented. The manual does not provide templates; ask the LLM to generate one if needed."
    },
    "generate_sbd_toe_skill": {
      previous_description: "GERA A PARTIR DO PUBLICADO, SEM VALIDAR O TEU AMBIENTE — não instala, não configura e não verifica nada do teu lado: devolve o texto para TU instalares onde souberes. Use this tool when asked to 'create a skill for SbD-ToE', 'set up instructions', 'configure this client/agent to use SbD-ToE', 'configure yourself for role X', or 'integrate SbD-ToE'. Without arguments returns the canonical skill content from sbd://toe/agent-guide. With role= returns a role-specialised skill (format=skill) or an installable sub-agent definition (format=subagent) grounded on the role's manual slice — flavour=harnessed grants the mcp__sbd-toe__* tools (queries live); flavour=skilled embeds the frozen slice with no MCP tools. Save the returned content to suggested_path (or the client equivalent)."
    },
    "map_sbd_toe_review_scope": {
      previous_description: "Given a set of changed files, maps which SbD-ToE knowledge bundles should be reviewed, with explicit reasoning per path."
    },
    "get_sbd_toe_chapter_implementation_checklist": {
      previous_description: "The canon/20 'how to implement chapter NN' checklist — retrieval-grounded prose from the implementation profile (the operational 'Aplicação no Ciclo de Vida' guidance). Use to answer 'how do I implement chapter NN / this area?'. Coverage-preserving; cites chunk ids; nothing invented. For the level-sharp structured Definition-of-Done use get_guide_by_role(include_detail=true)."
    },
    "get_sbd_toe_operating_model": {
      previous_description: "The operating model — RACI, decision-rights, governance cadences, org-model — from the rollout playbook (implementation profile). Retrieval-grounded prose; coverage-preserving; nothing invented. Use to answer 'who is responsible / how do we govern the SbD rollout?'."
    },
    "get_sbd_toe_verification_matrix": {
      previous_description: "The EXPECTED side of verification: per requirement/control at a risk level, the validation method + expected evidence + EvidencePattern reference (the published patterns — totals declared per response). The deterministic complement of the auditor's expectation and the test-plan. Cited per row; coverage-preserving — declares the requirements with no EvidencePattern. Use to answer 'how do I prove chapter/level X?' — or 'how do I prove THESE requirements?' via requirement_ids (o fecho requisito→prova a partir do select)."
    },
    "assess_sbd_toe_implementation": {
      previous_description: "SERVE OS LIMIARES PUBLICADOS APLICADOS AOS VALORES QUE DECLARASTE — a leitura é tua: não mede, não verifica os teus valores e não emite juízo de suficiência. Aritmética sobre dado publicado. Progresso auto-declarado: compara os KPI submetidos com os limiares publicados por nível thresholds (metrics.json) → posture (below/at/above) + gaps per KPI. Stateless self-report — values in, posture out, nothing stored; thresholds never invented; an applicable KPI with no value is not_reported (never a pass). Use to answer 'am I compliant at L2 / where are my gaps?'."
    },
    "plan_sbd_toe_rollout": {
      previous_description: "CONSULTA À SEQUÊNCIA PUBLICADA — não planeia por ti: serve a ordem das fases que o Manual publica, mapeada aos capítulos que cada uma atravessa. O roteiro é teu; isto é o que existe para o fazeres. MVP — phase-ordered, the dependency DAG is deferred (declared, not faked). Grounded in the published runtime; nothing invented. Use to answer 'in what order do we roll out SbD?'."
    },
    "get_sbd_toe_macro_processes": {
      previous_description: "LEITURA PROGRAMA (0.20.0-beta.37) — «por onde começamos e com que SEQUÊNCIA?». Serve os cinco macro-processos MP-01..05 que o Manual publica (pergunta, continuidade, invariante, dono, participantes, percurso de capítulos, indicadores, pontos de controlo, evidência esperada, proporcionalidade L1-L3) e a **ORDEM DE ADOPÇÃO publicada**. A ordem deriva EXCLUSIVAMENTE das arestas `dependency`: as `feedback` são realimentação e ficam FORA dela — se entrassem, os cinco macro-processos ciclariam. NÃO é a leitura GUIDE (que requisitos se aplicam a uma tarefa) nem a IMPL (a capacidade de um capítulo): devolver os 274 requisitos, ou um capítulo isolado, seria responder a outra pergunta. Limites DECLARADOS na resposta: não existe entidade «programa» (recusa de curadoria, ratificada); a travessia MP↔fase do SDLC é lacuna publicada e não se deriva; e MacroProcess, capítulo e fase são três segmentações paralelas — `traverses_bundles` é percurso, nunca contenção."
    },
    "explain_sbd_toe_topic": {
      previous_description: "LEITURA CONSULT (0.20.0-beta.35) — «o que é que o Manual DIZ sobre X?», pergunta de CONHECIMENTO, sem tarefa e sem projecto. Atravessa o Manual: requisitos (com `applies_at`), ORIENTAÇÃO (práticas), PROVAS, AMEAÇAS, **ANTIPADRÕES** («o que NÃO fazer» — a metade que não tinha caminho próprio) e onde no ciclo. Distingue requisito de orientação e marca a proveniência manual-grounded. **`risk_level` é OPCIONAL aqui e ANOTA, nunca filtra** — uma pergunta de conhecimento não tem nível. Fronteira deliberada: o nível continua OBRIGATÓRIO na selecção (`select_sbd_toe_requirements`), no `prepare_sbd_toe_codegen_context` e na vista de capacidade, onde a pergunta é «o que se aplica ao MEU caso». Pede por conceito (`concern`) ou por estrutura (`category` / `chapter`)."
    },
    "get_sbd_toe_chapter_capability": {
      previous_description: "LEITURA IMPL (0.20.0-beta.34) — «a organização quer implementar o cap. N: que capacidade precisa de ter, como sabe que está capaz, e COMO MEDE?». Publica os KPIs que o MANUAL define para o capítulo, com os `thresholds_by_level` (L1/L2/L3) como dado — é isso que distingue MEDIR de listar — mais os ARTEFACTOS que a capacidade tem de produzir. NÃO é a leitura GUIDE: se a pergunta é «que requisitos se aplicam a ESTA tarefa», isso é `select_sbd_toe_requirements`. A resposta declara qual das duas recebeste no campo `reading`. Alcançável por capítulo (`chapter`), por KPI (`metric_id`) ou por dimensão (`dimension`); `risk_level` acrescenta o alvo desse nível. Fecha o ciclo com `assess_sbd_toe_implementation`, que avalia os valores que TU medires contra estes mesmos KPIs."
    },
    "get_sbd_toe_playbook": {
      previous_description: "CAMINHO NORMATIVO para cross-checks e playbooks (0.20.0-beta.33). Responde a «somos sujeitos ao DORA/NIS2/CRA/RGPD/AI-Act — como é que o SbD-ToE nos serve?» com o PLAYBOOK publicado pelo Manual: mapa artigo→capítulo→acção, fases com marcos e checklist de leitura, servidos com a AUTORIDADE declarada. Ao contrário do `search_sbd_toe_manual` (NÃO-NORMATIVO, leitura), esta superfície é normativa. Sem argumentos devolve o ÍNDICE (barato); `framework=\"DORA\"` os playbooks desse diploma; `playbook_id=…` as secções paginadas. Os EXEMPLOS ILUSTRATIVOS vêm em banda SEPARADA e nunca com o estatuto dos cross-checks. Framework sem cross-check publicado (ISO 27001, HIPAA, PCI-DSS, SOC2, FedRAMP, CSA STAR) devolve `status: \"no_cross_check\"` com o roadmap do próprio Manual — declarado, nunca improvisado. Toda a resposta traz a DELIMITAÇÃO: o SbD-ToE não é uma norma, e implementá-lo não é conformidade."
    },
    "map_sbd_toe_regulatory_activation": {
      previous_description: "Regulatory lens (reverse of provenance): given a framework (DORA, NIS2, CRA, RGPD), returns which SbD-ToE manual areas/chapters it activates, grouped with mapping + obligation counts per chapter (coverage-preserving — never a blind dump). Data from the published overlay mappings; nothing invented. Use to answer 'framework X → what do I need to implement?'."
    },
    "map_sbd_toe_applicability": {
      previous_description: "GRADUATED applicability (0.14.0): every chapter applies at every level — returns per-chapter authored demand (obrigatório/recomendado/opcional/specific) derived from the bundle, anchored on the chapter-01 canonical matrix; plus context-conditional bundles for the given technologies. projectRole adds a per-role view. Nothing is excluded by level.",
      previous_long_params: {
        "projectRole": "Papel canónico do vocabulário publicado. **AFECTA a resposta**: produz a vista `role_view` por capítulo (as user stories atribuídas a este papel) — não altera é a activação de capítulos/controlos, que deriva do `riskLevel` e das `technologies`. Aliases publicados em `roles.json` são aceites e a resposta declara a resolução em `role_vocabulary`. Os valores legados desta tool (`architect`, `security`, `manager`) continuam aceites mas NÃO são papéis do vocabulário: devolvem vista vazia, declarada.",
      }
    },
    "read_sbd_toe_resource": {
      previous_description: "Mirror of resources/read for clients without MCP resource support (e.g. Claude Desktop): returns the content of any server resource by URI — including templated ones with the value in the URI (e.g. sbd://toe/codegen-instructions/codegen). Makes the codegen-instructions reference copy (slots + detail_encoding legend) resolvable on ANY client, and sbd://toe/version readable as a tool. Valid URIs: sbd://toe/agent-guide, sbd://toe/chapter-applicability/{riskLevel}, sbd://toe/quick-start, sbd://toe/model, sbd://toe/activation-vocabulary, sbd://toe/index-compact, sbd://toe/ontology, sbd://toe/skill/{role}, sbd://toe/subagent/{role}, sbd://toe/codegen-instructions/{mode}, sbd://toe/version, sbd://toe/grounded-codegen-guide. Unknown URI returns a declared error listing the valid set (never silent)."
    },
    "trace_sbd_toe_requirement_sources": {
      previous_description: "Onde está a FONTE de cada requisito: fontes DIRECTAS (source_anchors — autoria do Manual, marcador «Fontes») e cadeia COMPENSADA REQ→CTRL→ACO→fontes com tipo/confiança por salto (rótulo coverage_compensated — COBERTURA por correspondência entre modelos, NÃO autoria; related não cobre). Servida verbatim da superfície publicada (contrato v1.17 §1.24); os sem-fonte-declarada vêm DECLARADOS; ids desconhecidos idem."
    },
    "select_sbd_toe_requirements": {
      previous_description: "START HERE — para qualquer tarefa concreta esta é a 1ª tool. Arranque: lê sbd://toe/agent-guide (read_sbd_toe_resource); setup_sbd_toe_agent é um PROMPT MCP — clientes sem prompts (p.ex. Desktop) não o expõem: segue directo por aqui. DECLARATIVO PRIMEIRO (contrato v1.18-beta, linha 0.20): TU tens o contexto — lê o pedido, o código e a conversa e DECLARA o que interpretaste (risk_level, concerns, exposure, data_sensitivity, technologies, changed_files). EU NÃO INTERPRETO PROSA: respondo com o que o KG sabe sobre o declarado, mais as adjacências do grafo, de forma reproduzível. Vocabulário fechado em sbd://toe/activation-vocabulary. O `task` fica REGISTADO para auditoria e NÃO influencia o resultado; sem nenhuma declaração devolvo needs_input com o vocabulário e candidatos A CONFIRMAR (nunca adivinho, nunca devolvo zero em silêncio); a baseline do nível pede-se explicitamente (mode='baseline'); o motor inferencial antigo fica em mode='discover' (exploratório). The MP1 selection operation (Classificar → Seleccionar): which requirements apply to THIS task in THIS context. Composes the reference semantics the published ontology declares — baseline (cap. 02 base catalogue, by risk level) ∪ domain chapters activated by the DECLARED activators (concerns, exposure, data_sensitivity, technologies, changed_files) ∪ the categories the published vocabulary promises ⊕ regulatory overlay (extend) — then narrows deterministically by those same declarations. The task text is NEVER an activator in declarative mode (it is recorded context; it is only an engine in mode='discover'). Returns the bands: selected[] (each with its selection_trace: source/trigger/score), narrowed_out[] (eligible-without-signal, grouped by category, with reason), excluded_by_level[] and out_of_scope_chapters (what no declaration activated, by chapter and count, with how to bring it in) — never silent, and the SCOPE of that promise is the universe, not just the baseline. Paginated. coverage pagina `selected` por ORDEM DE ID (alfabética por categoria: ACC primeiro, VAL por último) — NÃO é ordem de relevância, e com uma selecção grande as últimas categorias ficam nas páginas finais (ex.: VAL em offset=200). Se procuras uma categoria específica, declara o concern que a activa, ou pede-a por estrutura (`categories=[…]`), em vez de paginar até lá. All data from the published deterministic runtime bundle — nothing is invented.",
      previous_long_params: {
        "chapters": "FORMA B — pedir por ESTRUTURA (0.20.0-beta.30). Ids de capítulo do catálogo publicado (`list_sbd_toe_chapters`), ex.: [\"14-governanca-contratacao\"]. Declaração VERDADEIRA e verificável: não depende de existir um atalho de `concerns` nem de inventar `changed_files`. Mesmas bandas, mesmo traço (`layer: \"declared_structure\"`), mesmos denominadores. Um valor que o catálogo não conhece vem em `unknown_structural`.",
        "detail": "Nível de SERIALIZAÇÃO da resposta (0.20.0-beta.26; default `full` = comportamento anterior, byte-idêntico). `standard` e `minimal` movem as justificações DISTINTAS do `selection_trace` para `selection_trace_legend` e deixam cada item a referi-las em `trace` — medido: −40% e −48% de payload numa selecção de 115 requisitos (12 justificações distintas para 115 entradas), com o MESMO conjunto de ids. Dieta de serialização, nunca de conteúdo: nenhum id e nenhuma justificação se perdem. `minimal` elide ainda `type` e `source_chapter` (deriváveis).",
      }
    },
    "consult_security_requirements": {
      previous_description: "Deterministic resolution of security requirements, controls and artifacts for a given application context. Filters requirements by risk level, optionally narrows by concern domains (auth, logging, api, etc.), then resolves controls via the published runtime bundle, complementing with ontology domain_mapping when needed. Requirements with no published control link are served and declared in coverage_gaps (never omitted). Os corpos devolvidos são PROJECÇÕES (id/name/category/type) — detalhe completo via resolve_entities; ≤3 concerns por chamada (âmbito recomendado; maxItems no schema). All data comes from the published SbD-ToE deterministic runtime bundle — nothing is invented.",
      previous_long_params: {
        "concerns": "Concern domains DECLARADOS (intersecta com o filtro de nível, não o substitui). Conjunto FECHADO de 24 valores, gerado do mesmo vocabulário que sbd://toe/activation-vocabulary publica (com o que cada valor activa e quantos requisitos traz por nível). Valores fora do conjunto são DECLARADOS na resposta (unknown_concerns), nunca descartados em silêncio. O `maxItems: 5` NÃO é um limite do vocabulário: é um tecto de PAYLOAD medido (5 concerns ≈4,3k tk) — o ensino recomenda ≤3.",
      }
    },
    "get_threat_landscape": {
      previous_description: "ROTEAMENTO ≠ COBERTURA (0.20.0-beta.29): aceita os 24 concerns do vocabulário sem erro, mas só 11 têm capítulo de ameaças PRÓPRIO — architecture, build, deployment, distribution, iac, logging, monitoring, release, supply_chain, testing, threat_modeling. Para os outros 13 as ameaças chegam pelos capítulos onde se DEFINEM os controlos que o concern activa: são reais e do âmbito activado, mas NÃO são «as ameaças deste domínio». A resposta declara-o em `routing_basis` (`domain_chapter` | `activated_controls`) — e a tabela acima diz-to ANTES de gastares a chamada. Em detail='standard'/'minimal' os nomes e ids dos controlos vêm por REFERÊNCIA à `associated_control_legend` — a promessa de campos completos é do detail='full'. ORDEM: por PERTENÇA ao âmbito declarado — capítulo de domínio dos concerns primeiro, depois os restantes capítulos activados, e os caps. 01/02 (classificação e meta-ameaças de PROCESSO) por último; dentro de cada escalão, mitigation_confidence, capítulo e id. A paginação segue esta ordem, por isso a página 1 É a parte relevante. Qualquer outro concern é VÁLIDO e tem requisitos, mas não é roteável AQUI: vem declarado em `unsupported_concerns`, e se TODOS os declarados forem não-roteáveis a resposta é `needs_input` em vez de um payload cheio de ameaças de governação sem relação com o pedido. Deterministic threat resolution for an application context using the SbD-ToE ontology threats pipeline. Returns threats from the published runtime bundle relevant to the active requirement/chapter scope (the defining chapters of activated controls count as in-scope), with structural mitigation confidence, antipattern enrichment, per-threat associated_control_ids (structural CTRL-* ids with declared derivation) and associated_control_names (readable control names, 233/233 since contract v1.16). Optionally narrowed by concern domains. All data comes from the published SbD-ToE deterministic runtime bundle — nothing is invented."
    },
    "get_guide_by_role": {
      previous_description: "Returns runtime-grounded practices, assignments and user stories for a given risk level, optionally filtered by role and/or lifecycle phase. Each assignment carries its required ARTIFACTS (the requirement→evidence link, served from the bundle since contract v1.16). Roles are resolved via canonical aliases (e.g. 'appsec' → 'appsec-engineer', 'sre' → 'devops-sre', 'security-engineer' → 'appsec-engineer'). Results grouped by role and phase. All data from the published SbD-ToE deterministic runtime bundle — nothing is invented."
    },
    "resolve_entities": {
      previous_description: "Low-level entity resolver over the published SbD-ToE deterministic artefacts. Three sources are routed by record_type, each with its own provenance: (1) runtime v0 (data/publish/runtime/*.json) for requirement / control / threat / artifact and related links; (2) AppSec Core v1 (data/publish/runtime/v1/*) for appsec_slice, control_objective, mechanism, appsec_practice, appsec_artifact and appsec_relation; (3) regulatory overlay (data/publish/overlay/*) for regulatory_framework, regulatory_obligation, regulatory_mapping and regulatory_playbook. Query any entity type by record_type with optional field filters. Supports dot-notation for nested fields (e.g. 'applicable_levels.L2'), comparison operators ({gte, lte} for numbers, {in: [...]} for set membership), and array membership checks. If the regulatory overlay is not published in this deployment, regulatory record types return total: 0 with an absent-reason note instead of throwing. Use this when the high-level tools (consult_security_requirements, get_threat_landscape, get_guide_by_role) do not cover your specific query. All data from the published SbD-ToE deterministic artefacts — nothing is invented.",
      previous_long_params: {
        "record_type": "Entity type to query. Runtime v0 (data/publish/runtime/*.json): requirement, control, practice, threat, user_story, assignment, role, phase, artifact, evidence_pattern, signal, antipattern, requirement_control_link, signal_evidence_link, antipattern_requirement_link, antipattern_threat_link. AppSec Core v1 (data/publish/runtime/v1/*): appsec_slice, control_objective, mechanism, appsec_practice, appsec_artifact, appsec_relation. Regulatory overlay (data/publish/overlay/*): regulatory_framework, regulatory_obligation, regulatory_mapping, regulatory_playbook. Read sbd://toe/ontology to see the schemas.",
      }
    },
    "trace_sbd_toe_graph": {
      previous_description: "Curated multi-hop traversal over the AppSec Core v1 relation graph (slices, control objectives, mechanisms, practices). Answers traceability questions the high-level tools do not expose directly. Pick a `lens`: 'slice_implementation' (a slice -> its control objectives -> the mechanisms that implement and practices that realize them); 'objective_realization' (a control objective -> its mechanisms + practices); 'mechanism_provenance' (a mechanism/practice -> the objectives it serves -> their slices). Optionally scope with `anchor` (an entity id). Results are deterministic and paginated (total + cursor; never silently truncated). All edges from the published deterministic runtime — nothing is invented."
    },
    "prepare_sbd_toe_codegen_context": {
      previous_description: "MONTA CONTEXTO, NÃO AGE — não escreve, não altera e não valida o teu código: reúne o contexto determinístico e citável para TU gerares. Contexto grounded, em porções, para um LLM a jusante gerar, review or plan tests for code. This tool DOES NOT generate code and DOES NOT edit files. It runs a scope gate (rejecting vague or overly broad asks), an auditable semantic activation step (explicit concerns, single-token lexicon, compound phrases such as 'endpoint seguro', PT/EN alias expansion via the semantic gateway, and a whole-word intent classifier — every activation carries a deterministic score in [0,1]), and deterministic resolution against runtime v0, runtime v1 and the regulatory overlay. Returns one of four statuses: ready_for_codegen, needs_clarification, needs_decomposition, unsupported_scope. On ready_for_codegen the output carries activation_trace (with score, source and reason), activated_scope, g2_context, manual_grounding, regulatory_overlay, citations (0.21 §3: invertido em todos os níveis — legenda por fonte + ids referenciados por caminho; citation_map já não existe), adjacency (0.21 §2, em TODOS os níveis: os sinais do vocabulário que NÃO declaraste e que mudariam o conjunto, com quantos ids cada um acrescentaria — aritmética sobre a declaração, nunca leitura da tarefa; resumo top-5 + denominadores; detalhe inline em standard/full, por referência em lista), completeness_report (incl. `verification`: denominadores da verificação fundida), llm_codegen_instructions and security_rationale_template — with provenance for each section. 0.21 §1 — O REQUISITO FUNDIDO: cada requisito activado é UM objecto {id, name, type, description, verify, evidence}, verbatim do bundle, em TODOS os níveis — a descrição nunca sai; `verify`/`evidence` são o padrão de evidência do próprio requisito (1:1). Já não há bloco g2_context.evidence_patterns nem cap: o que não vai inline (evidence_pattern_id, control_id, expected_artifact_type_ids) vem por referência executável (completeness_report.verification.by_ref → get_sbd_toe_verification_matrix). No canonical IDs are ever invented; names are surfaced only when manual_rastreabilidade publishes them.",
      previous_long_params: {
        "selection_mode": "Semântica da SELECÇÃO (não confundir com `mode`, que é codegen/review/test-plan). declarative (default, contrato v1.18-beta): o conjunto vem do que DECLARASTE (concerns/exposure/data_sensitivity/technologies/changed_files) — sem declarações devolvo needs_input com o vocabulário; o `task` serve para grounding/citações e auditoria, não para escolher requisitos. discover: motor inferencial histórico (a prosa activa), exploratório.",
        "detail": "Nível da resposta (0.21 §5): o eixo é «o que está INLINE e o que está POR REFERÊNCIA» — a descrição de cada requisito nunca sai, em nenhum nível, e o conjunto de ids citáveis é o mesmo em todos (invariante 3). 'lista': todo o requisito activado completo e verbatim (id, name, type, description, verify, evidence) + ids citáveis (`citations` invertido) + instruções e template inline; manual_grounding por referência (counts + entries_ref → 'full'); relations por referência (relations_ref, ou include_relations=true); trace só com debug=true; adjacência em RESUMO (top-5 do que NÃO declaraste e mudaria o conjunto + denominadores) com detail_ref. 'standard': o que a lista promete E a adjacência DETALHADA inline (todos os sinais). 'full' (default): o que o standard promete E manual_grounding verbatim inline, relations_ref executável (include_relations=true inlina-as), activation_trace inline, citations invertido — sem tecto, preço declarado em size_estimate. Em lista/standard as relations SAEM (relations_summary com a contabilidade exacta; 0.21 §3). TECTO de requisitos por chamada (ratificado 2026-09-25): lista 83, standard 88 (envelopes herdados 8.450/9.200 tk); acima ⇒ needs_decomposition com requirement_ceiling e divisão ensinada. 'ultrathin' retirou-se (cortava a descrição); 'minimal' passou a 'lista' — ambos devolvem erro que diz para onde foram.",
      }
    },
  }
} as const;
